-- CreateTable
CREATE TABLE "notas_servico" (
    "id" SERIAL NOT NULL,
    "arquivoOrigem" TEXT NOT NULL,
    "tipoDocumento" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Necessita revisão',
    "chaveAcesso" TEXT,
    "numero" TEXT NOT NULL DEFAULT '',
    "dataEmissao" TIMESTAMP(3),
    "competencia" TEXT NOT NULL DEFAULT '',
    "prestadorCnpj" TEXT NOT NULL DEFAULT '',
    "prestadorNome" TEXT NOT NULL DEFAULT '',
    "prestadorMunicipio" TEXT NOT NULL DEFAULT '',
    "prestadorSimplesNacional" BOOLEAN NOT NULL DEFAULT false,
    "tomadorCnpj" TEXT NOT NULL DEFAULT '',
    "tomadorNome" TEXT NOT NULL DEFAULT '',
    "tomadorMunicipio" TEXT NOT NULL DEFAULT '',
    "codigoTributacaoNacional" TEXT NOT NULL DEFAULT '',
    "itemServicoCodigoBase" TEXT,
    "descricaoServico" TEXT NOT NULL DEFAULT '',
    "valorServico" DOUBLE PRECISION,
    "aliquotaIss" DOUBLE PRECISION,
    "issRetido" BOOLEAN,
    "valorIss" DOUBLE PRECISION,
    "irrfDeclarado" DOUBLE PRECISION,
    "pccDeclarado" DOUBLE PRECISION,
    "valorLiquido" DOUBLE PRECISION,
    "camposNaoEncontrados" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "textoExtraido" TEXT NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "notas_servico_pkey" PRIMARY KEY ("id")
);
